version: '3.9'
services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    environment:
      REDIS_URL: redis://redis:6379
      API_PORT: 4000
    ports:
      - '4000:4000'
    depends_on:
      - redis

  worker:
    build:
      context: ..
      dockerfile: infra/Dockerfile.worker
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile.web
    environment:
      API_INTERNAL_URL: http://api:4000
    ports:
      - '3000:3000'
    depends_on:
      - api
